from os import environ
PRODUCER_SOAP_PASS = environ['PRODUCER_SOAP_PASS']
PRODUCER_SOAP_USER = environ['PRODUCER_SOAP_USER']
PPAK_SOAP_USER = environ['PPAK_SOAP_USER']
SIMI_DNS_NAME_ENDPOINT_TEMPLATE = environ['SIMI_DNS_NAME_ENDPOINT_TEMPLATE']
SIMIP3_DNS_NAME_ENDPOINT_TEMPLATE = environ['SIMIP3_DNS_NAME_ENDPOINT_TEMPLATE']
HEADERS = {'content-type': 'text/xml'}