from os import environ

ESS_CHAT_ID = environ["ESS_CHAT_ID"]
PPAK_STANDBY_CONNECTION_STRING = environ["PPAK_STANDBY_CONNECTION_STRING"]
DEFAULT_ORACLE_USER = environ["DEFAULT_ORACLE_USER"]
DEFAULT_ORACLE_PASS = environ["DEFAULT_ORACLE_PASS"]
PPAK_SOAP_URL = environ["PPAK_SOAP_URL"]
DEV_SOAP_URL = environ["DEV_SOAP_URL"]
DEV_DOC_CONNECTION_STRING = environ["DEV_DOC_CONNECTION_STRING"]
TG_BOT_USERNAME = environ["TG_BOT_USERNAME"]
